"""Coloured roles...

Revision ID: e761b419fc11
Revises: d7d9dac11e48
Create Date: 2023-02-22 23:19:43.948070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e761b419fc11'
down_revision = 'd7d9dac11e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=150), nullable=True))
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.create_foreign_key(None, 'role', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
